version: "3.8"

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - sftp_data:/home
    ports:
      - "2222:22"
    command: >
      bronx:bronx:::ingress/
      healtheconn:healtheconn:::ingress/
      grrhio:grrhio:::ingress/
      healthix:healthix:::ingress/
      healthelink:healthelink:::ingress/
      hixny:hixny:::ingress/
      observe:pass:::log/
  workflow:
    build:
      context: .
      dockerfile: Dockerfile.workflow
      args:
        - REPO_URL=https://github.com/qe-collaborative-services/1115-hub.git
    volumes:
      - sftp_data:/SFTP
    depends_on:
      - sftp

volumes:
  sftp_data:
